Improve compatibility with ROS2 distros
fixposition/fixposition_driver pull request #18
Opened 2023-04-19 23:15 UTC by rachit-aggarwal

Current build on humble yields a deprecation warning [seen here](https://github.com/fixposition/fixposition_driver/actions/runs/4738633288/jobs/8412699218). Latest [ROS2 Humble (> Nov 2022)](https://github.com/ros2/ros2/pull/1350) employs [`rosidl=3.1.4`](https://github.com/ros2/rosidl/blob/3.1.4/rosidl_cmake/cmake/rosidl_target_interfaces.cmake#L55) which currently handles the issue raised in the warning. However, older Humble versions produce build errors. This change incorporates the warning suggestion for improved compatibility.

2023-04-20 12:16 UTC, souryavarenya requested changes
Hi @rachit-aggarwal! This PR is very much appreciated. 

I have a minor suggestion upon which we'd be glad to test it internally.

2023-04-20 12:16 UTC, souryavarenya commented on fixposition_driver_ros2/CMakeLists.txt
> +endif()
How about we compact this a bit?

```suggestion
if($ENV{ROS_DISTRO} MATCHES "humble|rolling")
  rosidl_get_typesupport_target(
    cpp_typesupport_target
    ${PROJECT_NAME} "rosidl_typesupport_cpp"
  )
elseif($ENV{ROS_DISTRO} MATCHES "galactic|foxy|eloquent|dashing")
  rosidl_target_interfaces(
    ${PROJECT_NAME}_exec
    ${PROJECT_NAME} "rosidl_typesupport_cpp"
  )
else()
  message(FATAL_ERROR "Unsupported ROS_DISTRO")
endif()
```

2023-04-20 16:07 UTC, rachit-aggarwal commented on fixposition_driver_ros2/CMakeLists.txt
> +endif()
Thank you for the consideration and the suggestion.

2023-04-25 06:04 UTC, rachit-aggarwal commented
@souryavarenya Thanks again for the suggestion. I had accepted the changes and was wondering if you have an update.

2023-04-25 14:34 UTC, merged